---
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    # Use command module
  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

    # Use copy module
  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

    # Use command module
  - name: Enable and Configure System Module
    command: filebeat modules enable system

    # Use command module
  - name: Setup filebeat
    command: filebeat setup

    # Use command module
  - name: Start filebeat service
    command: service filebeat start

    # Use systemd module
  - name: Enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

  - name: Download the Metricbeat.deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install the Metricbeat.deb file
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in the metricbeat.yml file
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Run the metricbeat docker enable docker command
    command: metricbeat modules enable docker

  - name: Run the metricbeat setup command
    command: metricbeat setup

  - name: Start the metricbeat service
    command: service metricbeat start

  - name: Enable metricbeat on startup
    systemd:
      name: metricbeat
      enabled: yes
